### ISSUE TITLE
Logo and license

### ISSUE THREAD

**Issue by felix-hilden** [beartype/beartype-assets#1]
From beartype/beartype#8: Oi! Here be the final suggestions for the logo! The second one is 1/10 of the original size, approximately fitting e.g. the GitHub heading.

![beartype-logo](https://user-images.githubusercontent.com/25202257/105170987-623d4700-5b26-11eb-94b0-34eae53065a6.png)
![beartype-logo-small](https://user-images.githubusercontent.com/25202257/105170991-64070a80-5b26-11eb-8d76-a996eac34e63.png)

As for the license, I found this [discussion](https://softwareengineering.stackexchange.com/questions/318777/mit-license-vs-creative-commons-for-images-and-other-assets/318783) on the matter, stating that the content could be double-licensed. So we can use the MIT version in *Beartype*, but anybody working specifically with images that finds CC better to work with, can use that version. I'll make a PR already, so that if you're happy with it, you can already merge it and we can save a day of this asynchronous communication 😅

**Comment by leycec** [comment]
**Bwahala, take me now.** Your keyboard fingers must scintillate with creepy light like a lonely hospitalized ET, because *these logos are magic.*

![fingering ET](https://media.tenor.com/images/7f3b04ce40c3cea8cac31e81c7e452b1/tenor.png)

> As for the license, I found this discussion on the matter, stating that the content could be double-licensed.

Double license! Gadzooks, you're right. That's like the [double raindbow](https://www.youtube.com/watch/OQSNhk5ICTI) of the legal world, only less tear jerk-inducing and more enforceable in court.

Let's do this.
